import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
<<<<<<< HEAD
  title: "InfraDash",
  description: "Generated by create next app",
=======
  title: "INFRADASH",
  description: "Infrastructure Dashboard",
>>>>>>> bc404fb5fb1249137c88c5d553e3f2c5a96a5bf5
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
